- name: Create directory for LDAP certs
  ansible.builtin.file:
    path: "{{ ldap_certs_volume_params.driver_options.device }}"
    state: directory
    mode: "0755"
  become: true
  when:
    - ldap_state == 'started'

- name: Create directory for LDAP data
  ansible.builtin.file:
    path: "{{ ldap_data_volume_params.driver_options.device }}"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"
  become: true
  when:
    - ldap_state == 'started'

- name: Generate signed certs for openldap
  ansible.builtin.include_role:
    name: ca_cert_generate
  vars:
    cert_store: "{{ ldap_certs_volume_params.driver_options.device }}"
    cert_name: "server.crt"
    key_name: "server.key"
    secret_ca_passphrase: "{{ vault_secret_ca_passphrase }}"
    subject_alt_name:
      - "DNS:{{ hostvars[(groups['ca_servers'] | first)]['ca_name'] }}"
      - "IP:{{ ldap_host }}"
  when: generate_server_certs

- name: Template the openldap ca cert and ldif files
  ansible.builtin.copy:
    src: ./files/certs/
    dest: "{{ ldap_certs_volume_params.driver_options.device }}"
    mode: '0755'
  become: true
  when:
    - ldap_state == 'started'

- name: Create directory for phpLDAPadmin config
  ansible.builtin.file:
    path: "{{ ldap_phpconfig_volume_params.driver_options.device }}"
    state: directory
    mode: "0755"
  become: true
  when:
    - ldap_state == 'started'

- name: Template the phpldapadmin Configuration file
  ansible.builtin.template:
    src: config.php.j2
    dest: "{{ ldap_phpconfig_volume_params.driver_options.device }}/config.php"
    mode: '0755'
  become: true
  when:
    - ldap_state == 'started'

- name: Generate signed certs for phpldapadmin
  ansible.builtin.include_role:
    name: ca_cert_generate
  vars:
    cert_store: "{{ ldap_phpconfig_volume_params.driver_options.device }}"
    cert_name: "server.crt"
    key_name: "server.key"
    subject_alt_name:
      - "DNS:{{ hostvars[(groups['ca_servers'] | first)]['ca_name'] }}"
      - "IP:{{ ldap_host }}"
  when: generate_server_certs

- name: Copy ldap ca to phpLDAPadmin client directory
  ansible.builtin.copy:
    src: ./files/certs/ca.crt
    dest: "{{ ldap_phpconfig_volume_params.driver_options.device }}"
    mode: '0755'
  become: true
  when:
    - ldap_state == 'started'

- name: Create Docker Volume for phpLDAPadmin Config
  community.docker.docker_volume:
    name: "{{ ldap_phpconfig_volume_params.name }}"
    driver: "{{ ldap_phpconfig_volume_params.driver }}"
    driver_options: "{{ ldap_phpconfig_volume_params.driver_options }}"
    recreate: "options-changed"

- name: Create Docker Volume for LDAP Data
  community.docker.docker_volume:
    name: "{{ ldap_data_volume_params.name }}"
    driver: "{{ ldap_data_volume_params.driver }}"
    driver_options: "{{ ldap_data_volume_params.driver_options }}"
    recreate: "options-changed"

- name: Create Docker Volume for LDAP certs
  community.docker.docker_volume:
    name: "{{ ldap_certs_volume_params.name }}"
    driver: "{{ ldap_certs_volume_params.driver }}"
    driver_options: "{{ ldap_certs_volume_params.driver_options }}"
    recreate: "options-changed"

- name: Create LDAP network
  community.docker.docker_network:
    name: ldap
    driver: bridge
  register: ldap_network_result
